version: '3.8'

services:
  cdn-origin:
    build: .
    container_name: ateo-cdn-origin
    ports:
      - "6868:6868"
    environment:
      - NODE_ENV=production
      - UPLOAD_DIR=/app/data
      - PORT=6868
      - APP_URL=http://localhost:6868
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - cdn-network

networks:
  cdn-network:
    driver: bridge
